spring:
  application:
    name: smart-erp-server
  datasource:
    url: jdbc:mysql://localhost:3306/smart-erp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL6636
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000ms
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.smart.erp.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.smart.erp: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    # 界面上显示的标题
    doc-expansion: none
    operations-sorter: method